version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: abc_bank
      MYSQL_ROOT_PASSWORD: yourpassword
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/abc_bank
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: yourpassword
    depends_on:
      - db

volumes:
  db-data:
